import React from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '../components/Navbar';
import Sidebar from '../components/Sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}>  
        {/* Navbar at top */}
        <header className="w-full">
          <Navbar />
        </header>

        {/* Main content area: sidebar + page content */}
        <div className="flex flex-1 overflow-hidden">
          {/* Sidebar on the left */}
          <aside className="w-64 bg-gray-100 p-4 overflow-auto">
            <Sidebar />
          </aside>

          {/* Page content */}
          <main className="flex-1 overflow-auto p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}